ALTER TABLE upload_sessions ADD COLUMN IF NOT EXISTS name VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE upload_sessions ADD COLUMN IF NOT EXISTS storage_key TEXT NOT NULL DEFAULT '';
ALTER TABLE upload_sessions ADD COLUMN IF NOT EXISTS offset BIGINT NOT NULL DEFAULT 0 CHECK (offset >= 0);
